# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae9ca141256907ea93ecb57f8114fd6a62baf9dffcb0042e1a753815e7c444a510472f281410b72eb4b7067468420945472e597cbe618f4b06f07a3bb35e4711

test:
  secret_key_base: 678782571119182a522a44ebd43325eb4484dbd39fd3086fff29dffdf27317461078c0548c35714554622146ba96980e231b52d4b403780339afb8230e2f7961

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
